=== DmytroPavlyshyn/task14_JSON/src/main/resources/json/bankSchema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/root.json",
  "type": "array",
  "title": "The Root Schema",
  "items": {
    "$id": "#/items",
    "type": "object",
    "title": "The Items Schema",
    "required": [
      "bankId",
      "name",
      "country",
      "depositTypes",
      "depositor",
      "accountId",
      "amountOnDeposit",
      "profitability",
      "duration"
    ],
    "properties": {
      "bankId": {
        "$id": "#/items/properties/bankId",
        "type": "integer",
        "title": "The Bankid Schema",
        "default": 0,
        "examples": [
          1
        ]
      },
      "name": {
        "$id": "#/items/properties/name",
        "type": "string",
        "title": "The Name Schema",
        "default": "",
        "examples": [
          "Bank"
        ],
        "pattern": "^(.*)$"
      },
      "country": {
        "$id": "#/items/properties/country",
        "type": "string",
        "title": "The Country Schema",
        "default": "",
        "examples": [
          "Ukraine"
        ],
        "pattern": "^(.*)$"
      },
      "depositTypes": {
        "$id": "#/items/properties/depositTypes",
        "type": "array",
        "title": "The Deposittypes Schema",
        "items": {
          "$id": "#/items/properties/depositTypes/items",
          "type": "string",
          "enum": ["QUESTION", "EXPRESS","CALCULATED","ACCUMULATIVE","SAVING","METALLIC"],
          "title": "The Items Schema",
          "examples": [
            "CALCULATED"
          ]

        }
      },
      "depositor": {
        "$id": "#/items/properties/depositor",
        "type": "string",
        "title": "The Depositor Schema",
        "default": "",
        "examples": [
          "1"
        ],
        "pattern": "^(.*)$"
      },
      "accountId": {
        "$id": "#/items/properties/accountId",
        "type": "integer",
        "title": "The Accountid Schema",
        "default": 0,
        "examples": [
          1
        ],
        "minimum": 0.0
      },
      "amountOnDeposit": {
        "$id": "#/items/properties/amountOnDeposit",
        "type": "integer",
        "title": "The Amountondeposit Schema",
        "default": 0,
        "examples": [
          1
        ],
        "minimum": 0.0
      },
      "profitability": {
        "$id": "#/items/properties/profitability",
        "type": "integer",
        "title": "The Profitability Schema",
        "default": 0,
        "examples": [
          1
        ],
        "minimum": 0.0
      },
      "duration": {
        "$id": "#/items/properties/duration",
        "type": "object",
        "title": "The Duration Schema",
        "required": [
          "year",
          "month",
          "day"
        ],
        "properties": {
          "year": {
            "$id": "#/items/properties/duration/properties/year",
            "type": "integer",
            "title": "The Year Schema",
            "default": 0,
            "examples": [
              2018
            ],
            "minimum": 0.0
          },
          "month": {
            "$id": "#/items/properties/duration/properties/month",
            "type": "integer",
            "title": "The Month Schema",
            "default": 0,
            "examples": [
              12
            ],
            "minimum": 1.0,
            "maximum": 12.0
          },
          "day": {
            "$id": "#/items/properties/duration/properties/day",
            "type": "integer",
            "title": "The Day Schema",
            "default": 0,
            "examples": [
              1
            ],
            "minimum": 1.0,
            "maximum": 366.0
          }
        }
      }
    }
  }
}

=== DmytroPavlyshyn/task14_JSON/src/main/resources/json/bank2.json
[
  {
    "bankId": 0,
    "name": "Bank",
    "country": "Country",
    "depositTypes": [
      "CALCULATED"
    ],
    "depositor": "Depositor",
    "accountId": 0,
    "amountOnDeposit": 347,
    "profitability": 1,
    "duration": {
      "year": 2026,
      "month": 3,
      "day": 3
    }
  },
  {
    "bankId": 1,
    "name": "Bank",
    "country": "Country",
    "depositTypes": [
      "ACCUMULATIVE"
    ],
    "depositor": "Depositor",
    "accountId": 1,
    "amountOnDeposit": 385,
    "profitability": 1,
    "duration": {
      "year": 2023,
      "month": 3,
      "day": 3
    }
  },
  {
    "bankId": 2,
    "name": "Bank",
    "country": "Country",
    "depositTypes": [
      "METALLIC"
    ],
    "depositor": "Depositor",
    "accountId": 2,
    "amountOnDeposit": 384,
    "profitability": 1,
    "duration": {
      "year": 2026,
      "month": 3,
      "day": 3
    }
  },
  {
    "bankId": 3,
    "name": "Bank",
    "country": "Country",
    "depositTypes": [
      "METALLIC"
    ],
    "depositor": "Depositor",
    "accountId": 3,
    "amountOnDeposit": 578,
    "profitability": 1,
    "duration": {
      "year": 2022,
      "month": 3,
      "day": 3
    }
  },
  {
    "bankId": 4,
    "name": "Bank",
    "country": "Country",
    "depositTypes": [
      "METALLIC"
    ],
    "depositor": "Depositor",
    "accountId": 4,
    "amountOnDeposit": 367,
    "profitability": 1,
    "duration": {
      "year": 2023,
      "month": 3,
      "day": 3
    }
  }
]

=== DmytroPavlyshyn/task14_JSON/src/main/resources/json/bank.json
[
  {
    "bankId": 1,
    "name": "Bank",
    "country": "Ukraine",
    "depositTypes": [
      "CALCULATED",
      "ACCUMULATIVE"
    ],
    "depositor": "1",
    "accountId": 1,
    "amountOnDeposit": 1,
    "profitability": 1,
    "duration": {
      "year": 2018,
      "month": 12,
      "day": 1
    }
  },
  {
    "bankId": 1,
    "name": "Bank",
    "country": "Ukraine",
    "depositTypes": [
      "CALCULATED",
      "ACCUMULATIVE"
    ],
    "depositor": "1",
    "accountId": 1,
    "amountOnDeposit": 1,
    "profitability": 1,
    "duration": {
      "year": 2018,
      "month": 12,
      "day": 1
    }
  },
  {
    "bankId": 1,
    "name": "Bank",
    "country": "Ukraine",
    "depositTypes": [
      "CALCULATED",
      "ACCUMULATIVE"
    ],
    "depositor": "1",
    "accountId": 1,
    "amountOnDeposit": 1,
    "profitability": 1,
    "duration": {
      "year": 2018,
      "month": 12,
      "day": 1
    }
  },
  {
    "bankId": 1,
    "name": "Bank",
    "country": "Ukraine",
    "depositTypes": [
      "CALCULATED",
      "ACCUMULATIVE"
    ],
    "depositor": "1",
    "accountId": 1,
    "amountOnDeposit": 1,
    "profitability": 1,
    "duration": {
      "year": 2018,
      "month": 12,
      "day": 1
    }
  },
  {
    "bankId": 1,
    "name": "Bank",
    "country": "Ukraine",
    "depositTypes": [
      "CALCULATED",
      "ACCUMULATIVE"
    ],
    "depositor": "1",
    "accountId": 1,
    "amountOnDeposit": 1,
    "profitability": 1,
    "duration": {
      "year": 2018,
      "month": 12,
      "day": 1
    }
  },
  {
    "bankId": 1,
    "name": "Bank",
    "country": "Ukraine",
    "depositTypes": [
      "CALCULATED",
      "ACCUMULATIVE"
    ],
    "depositor": "1",
    "accountId": 1,
    "amountOnDeposit": 1,
    "profitability": 1,
    "duration": {
      "year": 2018,
      "month": 12,
      "day": 1
    }
  },
  {
    "bankId": 1,
    "name": "Bank",
    "country": "Ukraine",
    "depositTypes": [
      "CALCULATED",
      "ACCUMULATIVE"
    ],
    "depositor": "1",
    "accountId": 1,
    "amountOnDeposit": 1,
    "profitability": 1,
    "duration": {
      "year": 2018,
      "month": 12,
      "day": 1
    }
  },
  {
    "bankId": 1,
    "name": "Bank",
    "country": "Ukraine",
    "depositTypes": [
      "CALCULATED",
      "ACCUMULATIVE"
    ],
    "depositor": "1",
    "accountId": 1,
    "amountOnDeposit": 1,
    "profitability": 1,
    "duration": {
      "year": 2018,
      "month": 12,
      "day": 1
    }
  },
  {
    "bankId": 1,
    "name": "Bank",
    "country": "Ukraine",
    "depositTypes": [
      "CALCULATED",
      "ACCUMULATIVE"
    ],
    "depositor": "1",
    "accountId": 1,
    "amountOnDeposit": 1,
    "profitability": 1,
    "duration": {
      "year": 2018,
      "month": 12,
      "day": 1
    }
  },
  {
    "bankId": 1,
    "name": "Bank",
    "country": "Ukraine",
    "depositTypes": [
      "CALCULATED",
      "ACCUMULATIVE"
    ],
    "depositor": "1",
    "accountId": 1,
    "amountOnDeposit": 1,
    "profitability": 1,
    "duration": {
      "year": 2018,
      "month": 12,
      "day": 1
    }
  }
]
